# Generated by Django 4.2.27 on 2026-03-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_category_options_category_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='expire_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
